// AI极客俱乐部成员数据 - 52位成员完整档案
const membersData = [
  {
    id: 1,
    employeeId: "10046373",
    chineseName: "刘丹丹",
    englishName: "Dany Liu",
    businessLine: "Hardlines",
    department: "EC-ZJ Operation",
    group: "Technical Support",
    position: "Supervisor",
    location: "宁波",
    email: "dany.liu@intertek.com",
    phone: "",
    tools: "无",
    caseStudy: "半自动化的案例:之前通过Excel做过数据信息汇总表，通过粘贴系统数据到表单1，汇总表单列可以自动显示汇总数据信息。节省了汇总统计的时间。",
    interests: "想学习了解下AI或自动化软件/python等",
    projectIdeas: "暂无",
    expectations: "技术交流，经验学习",
    notes: "比较想运用AI提升自己的工作效率",
    techTags: ["📈 Excel数据分析师", "自动化报表专家"]
  },
  {
    id: 2,
    employeeId: "10042261",
    chineseName: "蔡海媛",
    englishName: "Helen Cai",
    businessLine: "Electrical",
    department: "NEC Operations",
    group: "SH Electronic-PS/BATT",
    position: "Sr. Project Engineer",
    location: "上海",
    email: "helen.cai@intertek.com",
    phone: "",
    tools: "很多",
    caseStudy: "人工智能训练师",
    interests: "人工智能训练师",
    projectIdeas: "暂无",
    expectations: "技术交流",
    notes: "爱学习",
    techTags: ["🎯 AI训练师", "人工智能专业人才"]
  },
  {
    id: 3,
    employeeId: "10033551",
    chineseName: "金莹",
    englishName: "Shadow",
    businessLine: "Business Assurance",
    department: "TS",
    group: "NA",
    position: "Supervisor",
    location: "上海",
    email: "shadow.jin@intertek.com",
    phone: "",
    tools: "Deepseek ,豆包",
    caseStudy: "暂无",
    interests: "简化工作流程",
    projectIdeas: "IATF标准排期中的可选性",
    expectations: "了解并学习AI，从而看看可否简化工作中的一些流程，提高工作效率",
    notes: "暂无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 4,
    employeeId: "10008499",
    chineseName: "诸林",
    englishName: "Tony Zhu",
    businessLine: "Softlines",
    department: "Textile CS",
    group: "Coordination",
    position: "Supervisor",
    location: "无锡",
    email: "tony.l.zhu@intertek.com",
    phone: "",
    tools: "VBA编程语言",
    caseStudy: "自己开发的软件(Turbo Support Center) ，适配业务线（Softlines）各个部门/科组（报告组，发票组，仓库，财务，QA等）的不同需求（如：前台可以按照快递号查询工作单，分样自动统计，Softlines 客服日常邮件通知，查询SM/MLP等，报告上传和报表全程自动定时发送等）。\n为Centrial Chemical Lab开发的实验室测试开单系统。目前已由wuxi site推广至浙江（杭州，海宁，宁波等chemical lab）。",
    interests: "有实践案例。详见上一个问题。",
    projectIdeas: "解决MARS与SM端数据交互问题，适配MARS实现数据 & 报表的无缝衔接上传",
    expectations: "进一步了解SM的软件逻辑，方便开发出适配业务线的功能模块，减少数据搜索过程中的时间浪费。\n获得SM端管理员的技术支持，优化SM在本地的推广。",
    notes: "愿意参与【AI故事分享】/【我要创新AI季节】等相关活动",
    techTags: ["🔧 VBA开发专家", "自动化系统构建者"]
  },
  {
    id: 5,
    employeeId: "10008505",
    chineseName: "邱芯薇",
    englishName: "Vickie Qiu",
    businessLine: "Quality Assurance",
    department: "NEC",
    group: "NA",
    position: "Asst. Manager",
    location: "无锡",
    email: "vickie.qiu@intertek.com",
    phone: "",
    tools: "Deepseek，Kimi，豆包",
    caseStudy: "AI自动生成PPT用于培训和活动策划",
    interests: "有案例，详见上一问。近期无相关学习证书。",
    projectIdeas: "AI制作视频用于培训",
    expectations: "了解更多的AI功能",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 6,
    employeeId: "10044565",
    chineseName: "王雯",
    englishName: "Wendy Wang",
    businessLine: "Transportation Technology",
    department: "Central Support",
    group: "NA",
    position: "Engineer",
    location: "上海",
    email: "wendy.ww.wang@intertek.com",
    phone: "",
    tools: "无",
    caseStudy: "尝试了用文学描述生成图片视频小说",
    interests: "学习了Power BI",
    projectIdeas: "无",
    expectations: "技术交流或者项目合作",
    notes: "无",
    techTags: ["🎬 AI多媒体创作者", "视觉内容专家"]
  },
  {
    id: 7,
    employeeId: "10043418",
    chineseName: "秦俊珠",
    englishName: "Judy Qin",
    businessLine: "Transportation Technology",
    department: "JQ-CS",
    group: "NA",
    position: "CS Officer",
    location: "上海",
    email: "judy.qin@intertek.com",
    phone: "",
    tools: "Deepdeek",
    caseStudy: "用于excel的函数和VBA代码，原本半小时的工作量缩减到2分钟，大大提高了工作效率和精准度。",
    interests: "继续探究Excel使用的多样性和实用性。",
    projectIdeas: "无",
    expectations: "业务线之间的交流，提高工作效率",
    notes: "目前正在学习使用如何用精准的语言给到AI，制作出自己需要的图片。",
    techTags: ["⚡ Excel自动化达人", "VBA效率提升者"]
  },
  {
    id: 8,
    employeeId: "10014248",
    chineseName: "谢浙囡",
    englishName: "Anna ZN Xie",
    businessLine: "Chemical Lab",
    department: "CCL",
    group: "Organic",
    position: "Sr. Manager",
    location: "海宁",
    email: "anna.xie@intertek.com",
    phone: "15868457806",
    tools: "deepseek  通义千问  豆包",
    caseStudy: "因为实验室同事忙于做实验无法实时查看手机微信信息，利用AI写程序代码，构建实验室信息传递系统，提高信息传递效率和准确性；AI辅助构建FCM测试流程跟进工具，引导FCM测试，加快测试速度，提高测试流程中信息传递效率；AI辅助下构建FCM测试报价及测试安排系统，能根据测试样品和材质快速生成测试项目，及列出测试报价单。",
    interests: "用自动化手段推进实验室的自动化流程，信息传递流程，加快实验室的信息化进度",
    projectIdeas: "最近正在做网页爬虫工具，进行标准查新工作",
    expectations: "希望在极客俱乐部有更多的信息交流，在交流的基础上有更多的创新思路和启发",
    notes: "能在极客俱乐部给个人更多赋能培训是最好的",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 9,
    employeeId: "10002623",
    chineseName: "陈焕钦",
    englishName: "Patrick Chen",
    businessLine: "Electrical",
    department: "NEC Operations",
    group: "HZ-LUM/Chem",
    position: "Manager",
    location: "杭州",
    email: "patrick.chen@intertek.com",
    phone: "",
    tools: "VS code + Github copilot, Claude code",
    caseStudy: "利用7中的工具，编写数款效率工具软件，譬如EMC预约排班系统，扫描文件自动处理系统等，其中最后一个报名参加了我要创新之AI季比赛，已提交相关资料",
    interests: "将自动化智能化融入工作，提高工作效率和工作愉悦度",
    projectIdeas: "智能化标准评估助手，降低工程师智力开销，提高标准评估的准确性",
    expectations: "技术交流，资源支持，获取新的idea",
    notes: "无",
    techTags: ["💻 代码工具高手", "效率软件开发者"]
  },
  {
    id: 10,
    employeeId: "10016157",
    chineseName: "马靖",
    englishName: "Jing Ma",
    businessLine: "Food",
    department: "NC-DL Office",
    group: "NC-Auditing",
    position: "Asst. Manager",
    location: "大连",
    email: "jing.ma@intertek.com",
    phone: "",
    tools: "办公小浣熊，剪映，灵光，智谱清言、豆包",
    caseStudy: "-年底数据分析，使用办公小浣熊对自己负责项目270+客户的数据进行趋势分析\n-使用灵光，给客户制作\"电子朱利安日期\"小程序，解决生产企业需要时时查询\"朱利安日\"的问题",
    interests: "/",
    projectIdeas: "- 正在参考HR前期推出关于AI的三次公关小程序的创意，想推出关于自己负责项目针对市场人员的培训小游戏，解决新市场人员对项目不熟悉的问题。\n-明年可能会学习\"飞书\"和\"扣子\"如何批量制作证书等（但目前只是计划，尚无途径）",
    expectations: "希望可以获得关于更多提供效率，共享文档和数据分析的AI方法",
    notes: "/",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 11,
    employeeId: "10048752",
    chineseName: "蒋梓毅",
    englishName: "Jeffrey Jiang",
    businessLine: "Electrical",
    department: "NEC Operations",
    group: "HN PV",
    position: "Testing Engineer",
    location: "海宁",
    email: "jeffrey.jiang@intertek.com",
    phone: "",
    tools: "deepseek、豆包",
    caseStudy: "无",
    interests: "无",
    projectIdeas: "无",
    expectations: "学习",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 12,
    employeeId: "10008957",
    chineseName: "刘晓辉",
    englishName: "Killy Liu",
    businessLine: "Chemical Lab",
    department: "CCL",
    group: "Management",
    position: "Asst. Manager",
    location: "青岛",
    email: "Killy.liu@intertek.com",
    phone: "15954245860",
    tools: "千问、豆包",
    caseStudy: "有。出报告时会有限值，如果单靠记录很繁琐，于是设计了EXCEL的小程序，可以自动判定结果，节省了大量的时间",
    interests: "有，多交流学习",
    projectIdeas: "有想法",
    expectations: "技术交流",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 13,
    employeeId: "10008777",
    chineseName: "齐洪山",
    englishName: "luke.Qi",
    businessLine: "Softlines",
    department: "Lab",
    group: "Physical",
    position: "Manager",
    location: "青岛",
    email: "luke.qi@intertek.com",
    phone: "18661871396",
    tools: "千问、Deepseek、豆包",
    caseStudy: "有，对于服装的缩率测试，每次都要测试很多部位，原来的方法是我们将量完的尺寸输入Excel表格，利用Excel表格计算缩率值，然后再copy到报告中的表格中。",
    interests: "有案例",
    projectIdeas: "有想法，也有创意项目，已经提交至AI创新季活动中",
    expectations: "技术交流",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 14,
    employeeId: "10008852",
    chineseName: "郑桃桃",
    englishName: "Tina.Zheng",
    businessLine: "Hardlines",
    department: "NC-Operation",
    group: "QD CM",
    position: "Manager",
    location: "青岛",
    email: "Tina.TT.zheng@intertek.com",
    phone: "1525421/4933",
    tools: "豆包，Deepceek，百度Ai，即梦，千问",
    caseStudy: "有，设置Teams聊天背景，百度Ai输入需求后，解决问题",
    interests: "有兴趣",
    projectIdeas: "有，数据知识库的创意项目，智能客服方向，正在创建中",
    expectations: "技术交流",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 15,
    employeeId: "10038668",
    chineseName: "曹宝鑫",
    englishName: "Gary Cao",
    businessLine: "Food",
    department: "Mgt-International Certification",
    group: "NA",
    position: "Supervisor",
    location: "青岛",
    email: "Gary.cao@intertek.com",
    phone: "17612180534",
    tools: "豆包等",
    caseStudy: "有，参与创新季，项目名称：利用AI的数据分析能力分配BRCGS注册费成本",
    interests: "有",
    projectIdeas: "有创意项目",
    expectations: "技术交流",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 16,
    employeeId: "10009850",
    chineseName: "张茜",
    englishName: "Vivian Zhang",
    businessLine: "Food",
    department: "EC-SH Office",
    group: "EC-Sales",
    position: "Asst. General Manager",
    location: "上海",
    email: "vivian.q.zhang@intertek.com",
    phone: "",
    tools: "豆包",
    caseStudy: "已提交AI故事",
    interests: "/",
    projectIdeas: "拓宽视野，跟大神发现更多可能；\n紧跟技术发展，满足求知欲；",
    expectations: "跨部门协作，把好的点子应用到食品部",
    notes: "/",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 17,
    employeeId: "10004974",
    chineseName: "高秀莲",
    englishName: "Helen Gao",
    businessLine: "Food",
    department: "Lab",
    group: "QA&EHS",
    position: "QA Officer",
    location: "上海",
    email: "QA Officer",
    phone: "",
    tools: "deepseek\\kim\\豆包",
    caseStudy: "日常涉及到程序文件编写，培训宣贯及考核。\n1) 编写程序文件时耗时很长，容易出现思路枯竭与歧义。现在我将要编写程序文件输入到Deepseek中帮我梳理方向和大纲，极大提高了文件编写效率。\n2) 以前制作培训PPT课件时，从编写内容到排版需花费半天时间，现在借助Deepseek可以生成PPT大纲内容，然后以markdown格式输出，借助kimi里PPT模板生成PPT，再进行整理，效率大大提升。\n3) 日常培训设计培训考题时，耗时较长，现在将考题的标准放到IMA知识库中，让它自动生成考题，效率提升。",
    interests: "/",
    projectIdeas: "制作短视频、方案设计",
    expectations: "各类AI工具的具体使用方法及应用场景，最新AI资讯",
    notes: "/",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 18,
    employeeId: "10026040",
    chineseName: "胡润泽",
    englishName: "Runze Hu",
    businessLine: "Electrical",
    department: "SC Operations",
    group: "GZ FS",
    position: "Asst. Manager",
    location: "广州-KXC",
    email: "runze.hu@intertek.com",
    phone: "",
    tools: "Ollama，豆包",
    caseStudy: "利用豆包获取说明书主要内容，帮助判断产品特性",
    interests: "通过AI提升工作效率，比如自动检查报告",
    projectIdeas: "自动检查测试数据是否超过限值范围；检查产品说明书是否有标准要求的警告语；自动检查铭牌信息；通过AI判断产品特性，需要用什么标准评估，然后自动给销售报价",
    expectations: "能够切实解决工作中的需求，提升工作效率",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 19,
    employeeId: "10041231",
    chineseName: "陈学谦",
    englishName: "Bill Chen",
    businessLine: "Electrical",
    department: "SC Operations",
    group: "GZ Operation-SMHA",
    position: "Project Engineer",
    location: "广州-KXC",
    email: "bill.xq.chen@intertek.com",
    phone: "",
    tools: "GEMINI",
    caseStudy: "周末空余时间尝试了用GEMINI搭建了一个marking label核对的工具",
    interests: "运用ai助力工作，无",
    projectIdeas: "周末空余时间尝试了用GEMINI搭建了一个marking label核对的在线工具\nhttps://safetylabel-check.vercel.app/\n（限制条件：国内网络只能选doubao，且算力有限，用完个人免费额度就无）",
    expectations: "无",
    notes: "无",
    techTags: ["🚀 AI技术爱好者", "创新探索者"]
  },
  {
    id: 20,
    employeeId: "10024223",
    chineseName: "巫清辉",
    englishName: "Joseph Wu",
    businessLine: "Electrical",
    department: "SC Operations",
    group: "SZ PPT Testing",
    position: "Sr. Project Engineer",
    location: "深圳-LH",
    email: "joseph.wu@intertek.com",
    phone: "",
    tools: "VBA、Labview、python",
    caseStudy: "1，用VBA自动把Excel里面的protocol复制到Word里面，节省写报告的时间。\n2，用python生成GB/T 26270的测试图片，用来测试显示器、投影仪等。\n3，用AI辅助写了Python程序，用来过滤粉红噪音信号，用于降噪测试。",
    interests: "很多测试每年数量不多，需要分包，主要会影响报告周期，如果能用AI辅助设计，用现有的测试设备完成测试，可以更好的把控报告周期，减少投诉。",
    projectIdeas: "用现有的设备完成喇叭阻抗曲线测试",
    expectations: "技术交流",
    notes: "办公电脑不能装软件，用来本地运行AI的话速度太慢。有些文档，像测试标准，只能本地分析，使用在线AI有侵权的风险，公司是否可以提供能本地运行AI的电脑。",
    techTags: ["⚡ Excel自动化达人", "VBA效率提升者"]
  },
  {
    id: 21,
    employeeId: "10051397",
    chineseName: "何培林",
    englishName: "Perry",
    businessLine: "Electrical",
    department: "SC Operations",
    group: "SZ Operations-EMC",
    position: "Project Engineer",
    location: "深圳-LH",
    email: "perry.he@intertek.com",
    phone: "13432056524",
    tools: "通义千问, AI Studio, Langchain",
    caseStudy: "使用Langchain框架+Deepseek R1搭建体检软件智能总检工作流，总检准确率达95%，替代医生人工总检工作，日产出最高达100份体检报告",
    interests: "模型架构搭建及智能体架构搭建。近期工作方面与AI有关",
    projectIdeas: "有想过，比如自动化标准解读，但没有可靠或高效的具体落地方案",
    expectations: "技术交流，探讨智能体搭建，神经网络架构设计等思路",
    notes: "无",
    techTags: ["🚀 AI技术爱好者", "创新探索者"]
  },
  {
    id: 22,
    employeeId: "10003434",
    chineseName: "张祺俊",
    englishName: "Storm Zhang",
    businessLine: "Softlines",
    department: "Textile Lab",
    group: "Physical 3",
    position: "Sr. Supervisor",
    location: "上海",
    email: "storm.zhang@intertek.com",
    phone: "",
    tools: "Chart deepseek",
    caseStudy: "快速检索出买家标准与常规标准两份文件的区别",
    interests: "紧跟时代，学习纺织方面的AI工具或实践案例；平台AI接入公司系统的可能性",
    projectIdeas: "AI用于管理方面，员工KPI数据考核和分析",
    expectations: "技术交流，好的创意点子",
    notes: "无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 23,
    employeeId: "10000293",
    chineseName: "刘欣",
    englishName: "Sammi Liu",
    businessLine: "Softlines",
    department: "Textile Lab",
    group: "Shrinkage",
    position: "Sr. Engineer",
    location: "上海",
    email: "sammi.liu@intertek.com",
    phone: "",
    tools: "网页小工具 Gemeni 单位换算",
    caseStudy: "S-Metrix 单位换算工具，国标、美标、欧标之前自由切换，高效且精准，可在部门里推广使用。",
    interests: "AI做视频，写歌及生活方面的应用；进一步优化和开发Mars系统的功能",
    projectIdeas: "希望可以进一步优化和开发Mars系统的功能，例如报告整理，Delay报告查询，RPA编程等。目前Mars系统太老，不支持这些数据处理功能。",
    expectations: "项目合作",
    notes: "无",
    techTags: ["🚀 AI技术爱好者", "创新探索者"]
  },
  {
    id: 24,
    employeeId: "10038209",
    chineseName: "冯林",
    englishName: "Simon Feng",
    businessLine: "Building&Construction",
    department: "OP-GZ BP",
    group: "Engineering-BPS",
    position: "Team Leader",
    location: "广州-Qixi",
    email: "simon.feng@intertek.com",
    phone: "",
    tools: "VBA, Uipath, Deepseek, 千问, KIMI, 豆包, Grok, Gemini.",
    caseStudy: "利用Uipath 解决制裁名单查询：\n每个月，需要把部门的所有客户，在美国OFAC网站上查询一遍，看客户是否是制裁名单内的公司。\n利用Uipath 每个月底，将部门所有的客户名单，一个个自动输入到美国OFAC网站中查询。如果是美国制裁的公司，将制裁信息复制下来。免除人工查询的步骤和时间。",
    interests: "1.利用AI解决实际问题\n2.前沿AI技术，信息\n3.日常生活和工作的AI工具深度应用。",
    projectIdeas: "想法一直都有，但要不断学习新的工具，跟高手请教。",
    expectations: "技术交流：跟高手学习，遇到问题可以相互解决，关注AI前沿技术。\n项目合作：有好的idea, 可以互相交流。成熟的项目路径可以互相借鉴。",
    notes: "无",
    techTags: ["⚡ Excel自动化达人", "VBA效率提升者"]
  },
  {
    id: 25,
    employeeId: "10046390",
    chineseName: "高凌宇",
    englishName: "Lingyu Gao",
    businessLine: "Softlines",
    department: "Textile",
    group: "Post Lab-Report Review",
    position: "Asst. Engineer",
    location: "广州-HP",
    email: "Lingyu.gao@intertek.com",
    phone: "",
    tools: "Deepseek, Uipath(RPA), VBA",
    caseStudy: "一、核心流程优化与工具开发\n针对团队协作中的痛点，通过AI开发解决方案，显著提升工作效率与系统稳定性。\n1. 数据表优化与重构：优化并维护迟单查询表、KEY_STATUS_MONITOR、追单表等核心数据表；重写PostLab流程表与Email发票跟进表，显著提升系统速度与使用体验。\n2. 协作冲突与性能优化：针对多人同时操作PostLab流程表导致的锁定与性能瓶颈，开发了基于宏的独立结论组做单表（Excel），成功实现分流，大幅减少资源争用，提升数据保存效率。\n3. 数据功能开发：开发做单表备注信息提取与自动分类功能、希音问题提取功能及追单率计数功能，增强数据支持与洞察能力。\n4. 效率工具创新：开发Clipmaster剪贴板工具，用于规范和快速复制结论提示，减少重复操作。\n二、业务流程自动化\n为多个重要业务线开发并维护自动化程序，减少人工操作，提升处理效率与准确性。\n5. 电商业务自动化：\n* 开发并维护希音（SHEIN）捞单并推送结果自动化程序。\n* 开发并维护淘宝/天猫质检报告数据自动获取与上传程序。\n6. 报告与摘要自动化：\n* 合作开发阿迪达斯（Adidas）上网自动化程序。\n* 开发并维护Delta Summary自动化程序。\n* 协助升级Lacoste Summary自动化程序。\n7. 报告生成与迁移：开发并维护报告生成自动化程序，并推动完成做单表至OneDrive共享的迁移与适配。\n三、SM系统测试支持\n8. 临时测试构建与管理：在SM系统中创建并维护Adhoc（临时）测试，累计新建1800个测试与更新管理4500个测试的，以支持CS快速开单，保证测试的准确性。",
    interests: "开发实用有趣的应用，近期通过AI探索一些热门应用的开发思路",
    projectIdeas: "通过AI开发壁纸，音乐播放器等简单应用",
    expectations: "技术交流",
    notes: "无",
    techTags: ["🔧 VBA开发专家", "自动化系统构建者"]
  },
  {
    id: 26,
    employeeId: "10050292",
    chineseName: "蔡婷婷",
    englishName: "Nicole",
    businessLine: "Softlines",
    department: "Textile",
    group: "CS",
    position: "CS Operation I",
    location: "广州-HP",
    email: "Nicole.cai@intertek.com",
    phone: "",
    tools: "python",
    caseStudy: "pdf转化excel",
    interests: "开发\npython机器学习",
    projectIdeas: "对接API",
    expectations: "项目方向\n技术交流",
    notes: "无",
    techTags: ["🐍 Python开发者", "智能化解决方案专家"]
  },
  {
    id: 27,
    employeeId: "10047006",
    chineseName: "何进艺",
    englishName: "Jimmy he",
    businessLine: "Softlines",
    department: "Footwear",
    group: "LIMS",
    position: "Sr. Engineer",
    location: "广州-HP",
    email: "Jimmy.he@intertek.com",
    phone: "",
    tools: "RPA: Uipath Studio, Ai: 腾讯元宝",
    caseStudy: "1. 使用元宝编写VBA代码。在工作当中，每天都需要批量去格式化Mars word文档，格式包括删除标题，调整页边距，段落缩进，表格对齐方式，表格宽度，表格特定边框颜色转换，通过使用元宝编写了VBA代码，再通过RPA调用VBA代码，实现批量秒转格式。\n2. 在工作当中，有的流程是重复且固定不变，因此创建了RPA机器人。其中一个机器人可以批量复制mars item, 提取mars item相关内容并进行数据处理，并将处理好的数据保存在excel文档当中，同时提取mars相关的信息并保存在excel表当中。处理完相关的数据后，机器人负责将相关信息填写到SM系统相关的表单，上传相关附件，并在excel总表填写创建记录等。",
    interests: "兴趣方向是PRA机器人, Ai,和Agent. 之前已完成uipath 官网studio X的相关课程，现在在学习uipath 官网Automation developer associate-training的相关课程。",
    projectIdeas: "主要将PRA运用到日常工作当中。",
    expectations: "希望从极客俱乐部进行技术交流，获取新的思路，学习前沿的技术，提高工作效率，促进公司和个人的进步。",
    notes: "无",
    techTags: ["⚡ Excel自动化达人", "VBA效率提升者"]
  },
  {
    id: 28,
    employeeId: "10043514",
    chineseName: "邝绮婷",
    englishName: "Qiting.Kuang",
    businessLine: "Softlines",
    department: "Textile",
    group: "Lab-Physical",
    position: "Engineer",
    location: "广州-HP",
    email: "Qiting.Kuang@intertek.com",
    phone: "",
    tools: "豆包",
    caseStudy: "无",
    interests: "无",
    projectIdeas: "无",
    expectations: "技术交流",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 29,
    employeeId: "10039134",
    chineseName: "王源添",
    englishName: "Steven",
    businessLine: "Softlines",
    department: "Textile",
    group: "Lab-Physical",
    position: "Technician",
    location: "广州-HP",
    email: "yuantian.wang@intertek.com",
    phone: "",
    tools: "PS/豆包",
    caseStudy: "无",
    interests: "无",
    projectIdeas: "无",
    expectations: "技术交流",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 30,
    employeeId: "10040040",
    chineseName: "陈洁仪",
    englishName: "Janus Chen",
    businessLine: "Hardlines",
    department: "SC-SZ Operation",
    group: "KMC Operation",
    position: "Technician",
    location: "深圳-IOT",
    email: "janus.chen@intertek.com",
    phone: "",
    tools: "豆包 Kimi deepseek python VBA（非擅长）",
    caseStudy: "自动抓取报告信息小工具，已申报AI季，详见AI季申报资料",
    interests: "自动化/数据分析，最近在学python",
    projectIdeas: "有想法，想让AI替我完成80%以上的工作",
    expectations: "技术指导",
    notes: "高额奖金就是最大的动力",
    techTags: ["⚡ Excel自动化达人", "VBA效率提升者"]
  },
  {
    id: 31,
    employeeId: "10017679",
    chineseName: "谢勇",
    englishName: "Allen Xie",
    businessLine: "Chemical Lab",
    department: "LIMS",
    group: "NA",
    position: "Manager",
    location: "广州-HP",
    email: "allen.xie@intertek.com",
    phone: "",
    tools: "元宝",
    caseStudy: "参与甲醛自动手臂AI项目，一种适用于甲醛测试自动化流程的机械臂辅助系统，项目正在进行中。",
    interests: "实验室AI自动化",
    projectIdeas: "有",
    expectations: "培训和技术交流",
    notes: "无",
    techTags: ["💻 系统开发者", "流程自动化专家"]
  },
  {
    id: 32,
    employeeId: "10001870",
    chineseName: "郭丽红",
    englishName: "Alison Guo",
    businessLine: "Inspection",
    department: "Project System Management",
    group: "IT-System",
    position: "Sr. Supervisor",
    location: "深圳-IOT",
    email: "alison.guo@intertek.com",
    phone: "",
    tools: "Uipath",
    caseStudy: "自2019起就开始自学uipath，在Inspection实施了大量的机器人自动化流程。",
    interests: "想了解Uipath+AI的结合应用",
    projectIdeas: "通过AI完成Python编程，实现客户的skip lot小程序。",
    expectations: "技术交流",
    notes: "暂无",
    techTags: ["🚀 AI技术爱好者", "创新探索者"]
  },
  {
    id: 33,
    employeeId: "10039797",
    chineseName: "吴晋波",
    englishName: "Bobo Wu",
    businessLine: "Hardlines",
    department: "SC-SZ Operation",
    group: "KMC Operation",
    position: "Asst. Supervisor",
    location: "深圳-IOT",
    email: "bobo.wu@intertek.com",
    phone: "",
    tools: "VBA，问小白，Deepseek",
    caseStudy: "通过AI给的vba代码，做了多个小工具\n1.批量打印文档\n2.模拟鼠标操作，在iMonitorout单\n3.按规则逐个打开PDF文档同时把文档从一个文件夹挪到另外一个文件夹",
    interests: "vba",
    projectIdeas: "准备做一个测试的fail Summary，方便登记及统计分析",
    expectations: "其他AI方面的应用",
    notes: "无",
    techTags: ["⚡ Excel自动化达人", "VBA效率提升者"]
  },
  {
    id: 34,
    employeeId: "10047573",
    chineseName: "马婧怡",
    englishName: "Penny Ma",
    businessLine: "Hardlines",
    department: "SC-SZ Operation",
    group: "KMC Technical Service",
    position: "Sr. Engineer",
    location: "深圳-IOT",
    email: "penny.ma@intertek.com",
    phone: "18683668329",
    tools: "Deepseek, Ima, 豆包",
    caseStudy: "经常使用AI帮助总结法规、标准内容，归纳重点，分析细节。此外，还经常利用AI快速抓取不同版本标准的细节差异，大大节省人力成本",
    interests: "无",
    projectIdeas: "希望基于AI的帮助可以实现：1. 自动化创建报告模板；2. 基于产品材质和出口市场自动推荐食品接触项目。问题在于专业化程度较高的情况下，内容的准确性无法保障",
    expectations: "希望借鉴一些AI能够实现的自动化流程",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 35,
    employeeId: "10010303",
    chineseName: "陈罡珣",
    englishName: "Tony Chen",
    businessLine: "Hardlines",
    department: "China-Marketing",
    group: "NA",
    position: "Sr. Manager",
    location: "广州-HP",
    email: "tony.chen@intertek.com",
    phone: "",
    tools: "1. 本地部署大模型；\n2. 利用cursor等IDE工具进行vibe coding；\n3. 利用dify搭建工作流；",
    caseStudy: "利用cursor搭建召回案例查询机器人，利用工作流搭建私人销售助理。1. 结合欧盟官方召回网站XML API接口，编写程序对欧盟召回信息进行调用；\n2. 用户输入\"公司名称\"以及\"品牌名称\"，利用大模型API接口（deepseek或Chatgpt），结合提示词对客户近期推出的新品进行全网查询并进行记录；\n3. 利用程序建立映射逻辑，让大模型对召回网站调取的\"产品类型\"（英文）进行中文产品信息的联想和罗列，然后对第2步查询的客户新品信息进行匹配；（这一步非常重要，不然很容易匹配不出结果）\n4. 匹配成功的话，大模型列出符合的召回信息，包括召回编号、产品类型、产地等；\n5. 结合第2步用户输入的\"公司名称\"以及\"品牌名称\"，结合提示词，让大模型再对客户的其他舆情信息进行全网搜索（包括官网、新闻稿、社交媒体、政府公告、投资者信息、行业媒体等），然后整理出供应链、ESG 等方向的最新变动、近期的投资、合作、并购、扩产以及重要的人事变动\n6. 最后结合客户新产品信息、召回风险、ESG、市场活动、供应链管理等舆情，通过预设的提示词，让大模型整理出一份更简洁、结构清晰的客户舆情报告；",
    interests: "vibe coding。自己学习中，没有考证书。",
    projectIdeas: "有，已参加公司举办的AI创意大赛并提交作品。",
    expectations: "技术交流",
    notes: "无",
    techTags: ["💻 系统开发者", "流程自动化专家"]
  },
  {
    id: 36,
    employeeId: "10023237",
    chineseName: "陈遥远",
    englishName: "Rena Chen",
    businessLine: "Finance",
    department: "Finance Operation-SC",
    group: "OTC",
    position: "Asst. Supervisor",
    location: "广州-KXC",
    email: "rena.chen@intertek.com",
    phone: "",
    tools: "豆包",
    caseStudy: "最近有使用AI帮我设计一些创意性的图片；以及请AI写一份内容详细丰富的家长讲堂课件大纲，并且再生成PPT和讲稿。",
    interests: "自动化办公方面；无证书",
    projectIdeas: "暂无",
    expectations: "鄙人对AI的了解还不够深入，主要是想要向AI技术纯熟的同事学习AI技巧，从而提高工作方面的效率",
    notes: "暂无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 37,
    employeeId: "10031070",
    chineseName: "王熙婷",
    englishName: "Cindy Wang",
    businessLine: "Hardlines",
    department: "EC-SH Operation",
    group: "Customer Services",
    position: "Sr. CS Officer",
    location: "上海",
    email: "cindy.xt.wang@intertek.com",
    phone: "",
    tools: "Deepseek & 豆包",
    caseStudy: "有，通过下发指令给到Deepseek，使其设计成为工作中可运用的工具，使整体效率提升30%。",
    interests: "通过AI不断提升工作效率。",
    projectIdeas: "有的，已参加AI创新项目。\n具体AI创新案例为：\n通过对买家protocol智能化的分配测试标准，帮助实验室更精准理解客户需求，提升一次测试通过率，增强服务竞争力。\n本项目通过AI技术实现买家协议与实验室测试的智能对接，从根本上解决标准执行偏差与报告整合低效的行业痛点。它不仅是一款工具升级，更是一次测试管理流程的数字化重构，具备广泛的行业推广价值和商业应用前景。\n使用AI后，AI让协议要求从\"藏在少数实验室里\"变成\"所有测试环节都看得见、对得上\"，测得更准，报告更快。具体为：\n•整合时间明显缩短，本来需要1个小时左右整合一单报告，现在只需要15分钟，缩短了75%。\n•报告准确性更高，测试前系统自动核对协议要求，避免标准偏差。将\"事后核对\"转为\"事前协同\"，从根本上杜绝标准偏差。",
    expectations: "技术交流。",
    notes: "暂无。",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 38,
    employeeId: "10044752",
    chineseName: "李洁宜",
    englishName: "Evelyn Li",
    businessLine: "Marketing&PR",
    department: "SC",
    group: "NA",
    position: "Marketing Executive",
    location: "广州-KXC",
    email: "evelyn.li@intertek.com",
    phone: "",
    tools: "deepseek、豆包、canva AI、即梦AI、Kimi、扣子空间",
    caseStudy: "背景：向内部同事分享10+数字营销案例视频\n方法：用deepseek生成视频脚本/文案，在剪映AI视频中导入视频文本，开启 \"AI 剪辑\"，自动匹配文本与画面节奏，同步生成配音，并添加字幕样式。封面图基于Canva AI制作，匹配品牌 VI 规范，自动将文案转化为符合品牌风格的海报。\n成果：成功缩短视频制作时间，提高工作效率。",
    interests: "AI在个性化营销与客户旅程优化中的应用；数据驱动营销自动化与预测分析。",
    projectIdeas: "暂时没有。",
    expectations: "希望了解AI在营销场景中的最新应用实例与技术边界，尤其是自然语言处理与预测模型如何更好与市场数据结合；\n获取行业工具评测、合规建议及AI营销趋势分享。",
    notes: "无。",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 39,
    employeeId: "10045926",
    chineseName: "许晓纯",
    englishName: "Kelly",
    businessLine: "Global IT",
    department: "Digital Innovation Lab",
    group: "NA",
    position: "Asst. Supervisor",
    location: "广州-KXC",
    email: "kelly.xc.xu@intertek.com",
    phone: "",
    tools: "deepseek",
    caseStudy: "利用deepseek生成代码，批量抓取数据、生成文件名等",
    interests: "兴趣方向：数据分析，视频生成等\n近期学习过Coursera的AI For Everyone（DeepLearning.AI）",
    projectIdeas: "最近想生成我家猫的拜年图片or在公司打工图片or代替我去运动的图片",
    expectations: "技术学习，项目合作",
    notes: "暂无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 40,
    employeeId: "10002201",
    chineseName: "刘艳红",
    englishName: "Only Liu",
    businessLine: "Inspection",
    department: "CS SC",
    group: "Customer Services",
    position: "Supervisor",
    location: "深圳-IOT",
    email: "Only.liu@intertek.com",
    phone: "",
    tools: "Excel and Uipath",
    caseStudy: "有，自动输入Excel的信息",
    interests: "没有",
    projectIdeas: "有",
    expectations: "技术交流和项目合作",
    notes: "我是初学者",
    techTags: ["🚀 AI技术爱好者", "创新探索者"]
  },
  {
    id: 41,
    employeeId: "10031159",
    chineseName: "李强",
    englishName: "Johnny Li",
    businessLine: "Food",
    department: "NC-BJ Office",
    group: "NC-Sales",
    position: "Asst. Sales Manager",
    location: "天津",
    email: "johnny.li@intertek.com",
    phone: "",
    tools: "豆包/Deepseek",
    caseStudy: "有，客户一些方案书，使用AI软件帮助后，可以出具相对满意的方案",
    interests: "没有具体的方向，不过想多学习一下AI使用",
    projectIdeas: "是的，希望后期遇到一些工作和生活的问题，可以多多借助AI的支持",
    expectations: "了解并学习AI，从而看看可否简化工作中的一些流程，提高工作效率",
    notes: "暂无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 42,
    employeeId: "10008770",
    chineseName: "朱伟",
    englishName: "Danny Zhu",
    businessLine: "Chemical Lab",
    department: "CCL",
    group: "Management",
    position: "Manager",
    location: "天津",
    email: "danny.zhu@intertek.com",
    phone: "",
    tools: "Deepseek ,豆包",
    caseStudy: "半自动化的案例:之前通过Excel做过数据信息汇总表，通过粘贴系统数据到表单1，汇总表单列可以自动显示汇总数据信息。节省了汇总统计的时间。",
    interests: "将自动化智能化融入工作，简化流程、提高工作效率",
    projectIdeas: "有，希望AI能代替人工做图谱分析，如果不能完全替代，那找出边界，把不能判断的提示出来，减少需要人工处理的工作量。",
    expectations: "希望可以获得关于更多提供效率，共享文档和数据分析的AI方法",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 43,
    employeeId: "10039181",
    chineseName: "戴晟",
    englishName: "Sally Dai",
    businessLine: "Hardlines",
    department: "NC-Operation",
    group: "QD CM",
    position: "Coordinator",
    location: "青岛",
    email: "Ada.xu@intertek.com",
    phone: "",
    tools: "Deepseek",
    caseStudy: "有",
    interests: "无",
    projectIdeas: "有，如何高效处理报告",
    expectations: "学习分享",
    notes: "无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 44,
    employeeId: "10044408",
    chineseName: "徐静",
    englishName: "Jane Xu",
    businessLine: "Food",
    department: "Mgt-International Certification",
    group: "NA",
    position: "Sr. Supervisor",
    location: "青岛",
    email: "Ada.xu@intertek.com",
    phone: "",
    tools: "Deepseek",
    caseStudy: "有",
    interests: "无",
    projectIdeas: "快速处理报告",
    expectations: "学习",
    notes: "无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 45,
    employeeId: "10041050",
    chineseName: "周拥军",
    englishName: "Aaron Zhou",
    businessLine: "Softlines",
    department: "Management",
    group: "NA",
    position: "Asst. Manager",
    location: "天津",
    email: "aaron.zhou@intertek.com",
    phone: "",
    tools: "Deepseek",
    caseStudy: "利用Deepseek对CFR-2022-title16-vol1-part303纺织纤维产品标识法案进行了翻译，并创建了该法案的解读文件，可用做公司内部的培训资料，对于准确理解标准提供了便利。和IT及相关同事一道开发了S组水洗吊布一键生成小程序。",
    interests: "对AI应用/自动化实践很感兴趣，尤其是带来管理创新和效率的提升",
    projectIdeas: "正在参与ERP系统数据化（原始数据终端）项目",
    expectations: "希望有机会参加一些技术交流活动",
    notes: "无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 46,
    employeeId: "10050791",
    chineseName: "王梓柔",
    englishName: "Serena Wang",
    businessLine: "Food",
    department: "Lab",
    group: "QA",
    position: "Engineer",
    location: "青岛",
    email: "giselle.wang@intertek.com",
    phone: "15834721072",
    tools: "豆包",
    caseStudy: "每天使用豆包询问专业术语和标准",
    interests: "无",
    projectIdeas: "有",
    expectations: "学习",
    notes: "无",
    techTags: ["☕ 豆包AI用户", "智能内容创作者"]
  },
  {
    id: 47,
    employeeId: "10044508",
    chineseName: "鲁牧",
    englishName: "Victor Lu",
    businessLine: "Hardlines",
    department: "NC-Operation",
    group: "TJ Lab",
    position: "Engineer",
    location: "天津",
    email: "victor.lu@intertek.com",
    phone: "",
    tools: "deepseek",
    caseStudy: "无",
    interests: "解决重复性问题/无",
    projectIdeas: "通过AI简化报告数据填写的流程，提高工作效率",
    expectations: "把想法变成现实",
    notes: "无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 48,
    employeeId: "10004862",
    chineseName: "刘海燕",
    englishName: "Sally Liu",
    businessLine: "Caleb Brett",
    department: "HCI Lab",
    group: "NA",
    position: "Supervisor(MS1)",
    location: "大连",
    email: "sally.hy.liu@intertek.com",
    phone: "",
    tools: "元宝 DEEPSEEK",
    caseStudy: "优化月报告表达、逻辑关系；搜索QA考题答案及分析；\n标准概要查询、做实验室介绍发言等",
    interests: "想学习发照片能生成视频动漫配音的技巧等；\n开发实用有趣的应用，近期通过AI探索一些热门应用的开发思路",
    projectIdeas: "希望基于AI的帮助可以实现：1. 自动化创建报告模板；\n2. 基于产品材质和出口市场自动推荐食品接触项目。\n问题在于专业化程度较高的情况下，内容的准确性无法保障",
    expectations: "鄙人对AI的了解还不够深入，主要是想要向AI技术纯熟的同事学习AI技巧，从而提高工作方面的效率；希望从极客俱乐部进行技术交流，获取新的思路，学习前沿的技术，提高工作效率，促进公司和个人的进步。",
    notes: "希望能与时俱进，享受AI时代的红利",
    techTags: ["🚀 AI技术爱好者", "创新探索者"]
  },
  {
    id: 49,
    employeeId: "10012560",
    chineseName: "冯洁菲",
    englishName: "Betty Feng",
    businessLine: "Hardlines",
    department: "NC-Operation",
    group: "TJ Admin",
    position: "Sr. Supervisor",
    location: "天津",
    email: "betty.feng@intertek.com",
    phone: "",
    tools: "无",
    caseStudy: "用Deepseek搜索过一些问题",
    interests: "了解AI和经验学习，看看可否应用到工作中",
    projectIdeas: "了解AI和经验学习，看看可否应用到工作中",
    expectations: "了解AI和经验学习，看看可否应用到工作中",
    notes: "无",
    techTags: ["💡 AI实践新手", "创意应用者"]
  },
  {
    id: 50,
    employeeId: "10041882",
    chineseName: "安毓川",
    englishName: "Charlie An",
    businessLine: "Hardlines",
    department: "NC-Operation",
    group: "TJ Lab",
    position: "Asst. Supervisor",
    location: "天津",
    email: "charlie.an@intertek.com",
    phone: "",
    tools: "Deepseek & 豆包",
    caseStudy: "有，通过下发指令给到Deepseek，使其设计成为工作中可运用的工具，使整体效率提升30%。",
    interests: "自动化办公方面；无证书",
    projectIdeas: "有，已参加公司举办的AI创意大赛并提交作品。",
    expectations: "技术交流：跟高手学习，遇到问题可以相互解决，关注AI前沿技术。\n项目合作：有好的idea, 可以互相交流。成熟的项目路径可以互相借鉴。",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  },
  {
    id: 51,
    employeeId: "10046957",
    chineseName: "任崇玲",
    englishName: "Leah Ren",
    businessLine: "Hardlines",
    department: "NC-Operation",
    group: "TJ Lab",
    position: "Sr. Engineer",
    location: "天津",
    email: "leah.ren@intertek.com",
    phone: "",
    tools: "Deepseek,百度AI",
    caseStudy: "有时对标准的理解不透彻，可以借助Deepsheek进行详细的理解和学习",
    interests: "无，多学习交流",
    projectIdeas: "无",
    expectations: "多学习新的知识",
    notes: "无",
    techTags: ["🧠 Deepseek深度用户", "AI辅助工作专家"]
  },
  {
    id: 52,
    employeeId: "10010598",
    chineseName: "武晓芳",
    englishName: "Niki Wu",
    businessLine: "Softlines",
    department: "Technical Support",
    group: "NA",
    position: "Sr. Supervisor",
    location: "天津",
    email: "niki.xf.wu@intertek.com",
    phone: "",
    tools: "Deepseek，Kimi，豆包、通义千问、剪映、元宝",
    caseStudy: "标准变更、标准比对、写总结性文件、写PPT",
    interests: "自动化/数据分析/创新/提高工作质量",
    projectIdeas: "暂无",
    expectations: "技术交流/项目合作//经验学习",
    notes: "无",
    techTags: ["🤖 AI工具多面手", "智能办公实践者"]
  }
];
